name: Version

on:
  push:
    branches: [ sdlc_semantic_release ]

jobs:

  version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
      - name: Generate semantic-release configuration
        run: |
          cat << EOF > .releaserc
          {
            "branches": [
              "sdlc_semantic_release"
            ],
            "plugins": [
              "@semantic-release/commit-analyzer",
              "@semantic-release/release-notes-generator",
              "@semantic-release/git"
            ]
          }
          EOF
      - name: Run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npx semantic-release --dry-run
